// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, Robot, request, robot;

  request = require('request');

  Promise = require('bluebird');

  Promise.promisifyAll(request);

  module.exports = Robot = (function() {
    function Robot(key, api) {
      this.key = key;
      this.api = api != null ? api : 'http://www.tuling123.com/openapi/api';
    }

    Robot.prototype.ask = function(info, options) {
      if (options == null) {
        options = {};
      }
      options.key = this.key;
      options.info = info;
      return request.getAsync(this.api, {
        qs: options
      }).then(function(res) {
        return Promise.resolve(JSON.parse(res.body));
      });
    };

    return Robot;

  })();

  if (require.main === module) {
    robot = new Robot('0a4114ff7687944016c9d50a07eb0f250', 'http://www.tuling123.com/openapi/api');
    robot.ask('你好', {
      userid: 'wwx'
    }).then(function(data) {
      console.log(data);
    });
  }

}).call(this);
