// Generated by CoffeeScript 2.3.1
(function() {
  var Promise, Robot, request, robot;

  request = require('request');

  Promise = require('bluebird');

  Promise.promisifyAll(request);

  module.exports = Robot = class Robot {
    constructor(key, api = 'http://www.tuling123.com/openapi/api') {
      this.key = key;
      this.api = api;
    }

    ask(info, options = {}) {
      options.key = this.key;
      options.info = info;
      return request.getAsync(this.api, {
        qs: options
      }).then(function(res) {
        return Promise.resolve(JSON.parse(res.body));
      });
    }

  };

  if (require.main === module) {
    robot = new Robot('0a4114ff7687944016c9d50a07eb0f250', 'http://www.tuling123.com/openapi/api');
    robot.ask('你好', {
      userid: 'wwx'
    }).then(function(data) {
      console.log(data);
    });
  }

}).call(this);
